package tsmodels

var (
	TsFmsExtLinkTbl      = "TS_FMS_EXT_LINK"
	TsFmsMenuBaseTbl     = "TS_FMS_MENU_BASE"
	TsFmsMenuTbl         = "TS_FMS_MENU"
	TsFmsMenuPinTbl      = "TS_FMS_MENU_PIN"
	TsFmsConnectTbl      = "TS_FMS_CONNECT"
	TsFmsConnectTypeTbl  = "TS_FMS_CONNECT_TYPE"
	TsFmsConnectStateTbl = "TS_FMS_CONNECT_STATE"
	TsFmsFieldTypeTbl    = "TS_FMS_FIELD_TYPE"
	TsFmsFieldTbl        = "TS_FMS_FIELD"
	TsFmsTagTbl          = "TS_FMS_TAG"
	TsFmsEquipTbl        = "TS_FMS_EQUIP"
	TsFmsEquipEdgeTbl    = "TS_FMS_EQUIP_EDGE"
	TsFmsSiteTbl         = "TS_FMS_SITE"
	TsFmsAlrmTypeTbl     = "TS_FMS_ALRM_TYPE"
	TsFmsAlrmCodeTbl     = "TS_FMS_ALRM_CODE"
	TsFmsAlrmTbl         = "TS_FMS_ALRM"
	TsFmsAlrmBandTbl     = "TS_FMS_ALRM_BAND"
	TsFmsAlrmRuleTbl     = "TS_FMS_ALRM_RULE"
	TsFmsAnlyStateTbl    = "TS_FMS_ANLY_STATE"
	TsFmsAnlyPredTbl     = "TS_FMS_ANLY_PRED"
	TsFmsAnlyCorrTbl     = "TS_FMS_ANLY_CORR"
	TsFmsAnlyCorrTagTbl  = "TS_FMS_ANLY_CORR_TAG"
	TsFmsAnlyDiagTbl     = "TS_FMS_ANLY_DIAG"
	TsFmsDigitalTwinTbl  = "TS_FMS_DIGITAL_TWIN"
	GfUserTbl            = "user"
	GfOrgUserTbl         = "org_user"
	GfOrgTbl             = "org"
)
